docs: venus-docs guideline
ipfs-force-community/dev-guidances pull request #28
Opened 2022-05-30 08:42 UTC by Fatman13

2022-05-30 08:42 UTC, Fatman13 commented
@diwufeiwen @dtynn 请求review。

2022-05-30 09:35 UTC, dtynn requested changes

2022-05-30 09:35 UTC, dtynn commented on 质量管理/文档/venus-docs文档规范.md
> +:::
这里的语法是不是不是标准 markdown 语法？
github 渲染不出来，考虑放进代码块里？

2022-05-30 09:35 UTC, dtynn commented on 质量管理/文档/venus-docs文档规范.md
> +:::
这里每个条目的换行之后的内容，需要加一层缩进，让使得他们在渲染结果中，和首行保持相同缩进
后面的都是

2022-06-01 07:29 UTC, dtynn requested changes

2022-06-01 07:29 UTC, dtynn commented on 质量管理/文档/venus-docs文档规范.md
> +	[相同目录可以直接用文件名](xiangtongmulu)
这里会被渲染，是不是考虑放进代码块？

2022-06-01 07:34 UTC, Fatman13 commented
@dtynn 大神，请求review。

2022-06-06 02:25 UTC, dtynn approved these changes
LGTM

2022-06-06 02:25 UTC, merged