docs: more publish detail
ipfs-force-community/dev-guidances pull request #48
Opened 2023-03-16 01:45 UTC by simlecode

2023-03-16 02:48 UTC, Fatman13 requested changes

2023-03-16 02:48 UTC, Fatman13 commented on 项目管理/Venus/版本发布管理.md
> +本文档规范了 `Venus` 项目团队内部发版流程，与社区同步最新 `Venus` 组件相关版本。部分流程参考了 `Lotus` 的 [release_flow](https://github.com/filecoin-project/lotus/blob/master/LOTUS_RELEASE_FLOW.md#mandatory-releases)。
手动点👍

2023-03-16 02:48 UTC, Fatman13 commented on 项目管理/Venus/版本发布管理.md
> +创建 `release` 分支时已更新版本号和 changlog，可以直接发版本
```suggestion
创建 `release` 分支时已更新版本号和 changlog，可以直接发 `vX.Y.X-rc[x]` 版本（x = 1, 2, 3...）。
```

2023-03-16 02:48 UTC, Fatman13 commented on 项目管理/Venus/版本发布管理.md
> +当合并到主分支的 `pr` 在开发分支也需要时，用  `rebase` 或者 `cherry-pick` 的方式合并到开发分支
```suggestion
当合并到主分支的 `pr` 在开发分支也需要时，用  `rebase` 或者 `cherry-pick` 的方式合并到开发分支。
```
咱们要不要都加个句号？😂 可能不是什么重点。

2023-03-16 02:48 UTC, Fatman13 commented on 项目管理/Venus/版本发布管理.md
>  ## 背景
找 shuqi 大佬也来 review 下？

2023-03-21 06:08 UTC, simlecode commented on 项目管理/Venus/版本发布管理.md
>  ## 背景
可以

2023-03-21 06:08 UTC, simlecode commented on 项目管理/Venus/版本发布管理.md
> +创建 `release` 分支时已更新版本号和 changlog，可以直接发版本
已修改

2023-03-24 01:36 UTC, Fatman13 commented
CC @elvin-du

2023-03-29 09:41 UTC, elvin-du approved these changes
LGTM

2023-03-29 09:41 UTC, elvin-du commented on 项目管理/Venus/版本发布管理.md
> +根据 `milestones` 的计划来创建开发分支，开发分支从当前 `master` 切出来。这就意味着开发分支可以有多个，每个开发分支代表一个版本，有助于做长期规划，将 `issue` 提前预设到版本对应的 `milestone`。
每个人开发时都需要创建一个branch，然后通过pr的方式进行协作。

2023-03-31 06:35 UTC, simlecode commented on 项目管理/Venus/版本发布管理.md
> +根据 `milestones` 的计划来创建开发分支，开发分支从当前 `master` 切出来。这就意味着开发分支可以有多个，每个开发分支代表一个版本，有助于做长期规划，将 `issue` 提前预设到版本对应的 `milestone`。
是的

2023-03-31 06:38 UTC, Fatman13 approved these changes
LGTM

2023-03-31 06:38 UTC, merged